version : '3'
services :
  csvserver:
    container_name : csvserver
    image : infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
      - type: bind
        source: ./inputdata
        target: /csvserver/inputdata
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml

